export const umkmData = [
    {
        id: 0,
        name: 'Kedai Kopi Senja',
        location: 'Yogyakarta',
        image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ownerName: 'Bapak Ilham',
        ownerAvatar: 'https://i.pravatar.cc/150?u=ilham',
        yearsActive: '5 tahun',
        grade: 'A',
        category: 'Kuliner',
        minInvest: 'Rp 1.000.000',
        fundingPct: 88,
        fundedAmt: 'Rp 35.200.000',
        targetAmt: 'Rp 40.000.000',
        desc: 'Kedai kopi specialty yang memberdayakan petani lokal dari lereng Merapi. Memiliki 2 outlet dan rencana ekspansi roastery.',
        storyQuote: '"Berkat pendanaan investor NEMOS, saya dapat membeli mesin roasting baru dan tidak lagi bergantung pada jasa sangrai pihak ketiga. Ini meningkatkan margin profit kami 15% sekaligus menjaga kualitas rasa kopi lebih konsisten hari demi harinya."',
        socialImpact: '👥 Memberdayakan 6 pemuda desa',
        revenueData: [40, 44, 48, 50, 55, 62],
        cut: '5%',
        roi: '14 – 17%',
        allocation: [
            { label: 'Mesin Roasting', pct: 60, color: '#1E3A5F' },
            { label: 'Renovasi Outlet', pct: 20, color: '#00C853' },
            { label: 'Stok Biji Kopi', pct: 10, color: '#FF9800' },
            { label: 'Marketing', pct: 10, color: '#6B7280' },
        ],
        roiRate: 0.16,
    },
    {
        id: 1,
        name: 'Tani Makmur Organik',
        location: 'Malang, Jawa Timur',
        image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ownerName: 'Ibu Listia',
        ownerAvatar: 'https://i.pravatar.cc/150?img=47',
        yearsActive: '3 tahun',
        grade: 'A',
        category: 'Agrikultur',
        minInvest: 'Rp 1.000.000',
        fundingPct: 60,
        fundedAmt: 'Rp 18.000.000',
        targetAmt: 'Rp 30.000.000',
        desc: 'Pertanian hidroponik modern yang menyuplai sayuran organik segar ke supermarket premium di Jawa Timur. Pertumbuhan stabil 8%/bulan.',
        storyQuote: '"Menjaga kualitas panen butuh greenhouse yang baik. Lewat skema RBF, kami tidak dipusingkan dengan cicilan tetap saat cuaca sedang buruk, karena bagi hasil menyesuaikan dengan hasil panen bulanan."',
        socialImpact: '🌱 100% Bebas Pestisida Kimia',
        revenueData: [25, 27, 29, 31, 33, 36],
        cut: '4%',
        roi: '12 – 15%',
        allocation: [
            { label: 'Greenhouse Baru', pct: 50, color: '#1E3A5F' },
            { label: 'Bibit Premium', pct: 25, color: '#00C853' },
            { label: 'Kendaraan Logistik', pct: 15, color: '#FF9800' },
            { label: 'Operasional', pct: 10, color: '#6B7280' },
        ],
        roiRate: 0.14,
    },
    {
        id: 2,
        name: 'Batik Cempaka',
        location: 'Solo, Jawa Tengah',
        image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ownerName: 'Ibu Ratna',
        ownerAvatar: 'https://i.pravatar.cc/150?img=32',
        yearsActive: '6 tahun',
        grade: 'B',
        category: 'Kerajinan',
        minInvest: 'Rp 100.000',
        fundingPct: 45,
        fundedAmt: 'Rp 9.000.000',
        targetAmt: 'Rp 20.000.000',
        desc: 'Batik tulis cap pewarna alami ramah lingkungan. Eksis di pasar domestik dan merambah pasar suvenir perusahaan internasional.',
        storyQuote: '"Saya bercita-cita melestarikan motif batik tulis kuno, namun kami sering kekurangan modal untuk bahan sutra. Dana investor akan difokuskan untuk memenuhi pesanan massal dari hotel di Bali."',
        socialImpact: '👵 15 Pengrajin Lansia Diberdayakan',
        revenueData: [15, 18, 17, 20, 22, 24],
        cut: '6%',
        roi: '18 – 22%',
        allocation: [
            { label: 'Kain & Sutra', pct: 35, color: '#1E3A5F' },
            { label: 'Pewarna Alami', pct: 30, color: '#00C853' },
            { label: 'Pemasaran Digital', pct: 25, color: '#FF9800' },
            { label: 'Operasional', pct: 10, color: '#6B7280' },
        ],
        roiRate: 0.20,
    },
    {
        id: 3,
        name: 'Dapur Nusantara',
        location: 'Bandung, Jawa Barat',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        ownerName: 'Ibu Sari',
        ownerAvatar: 'https://i.pravatar.cc/150?img=9',
        yearsActive: '4 tahun',
        grade: 'A',
        category: 'Kuliner',
        minInvest: 'Rp 1.000.000',
        fundingPct: 75,
        fundedAmt: 'Rp 37.500.000',
        targetAmt: 'Rp 50.000.000',
        desc: 'Usaha kuliner rumahan spesialis kue tradisional dan modern. Omzet stabil dengan pelanggan loyal.',
        storyQuote: '"Saya Ibu Sari, sudah 4 tahun membuat kue tradisional dari dapur rumah saya. Dengan dukungan investor NEMOS, saya bisa menambah oven industri dan mempekerjakan 2 balita tetangga saya."',
        socialImpact: '👩‍🍳 Ibu Rumah Tangga Mandiri',
        revenueData: [32, 35, 38, 36, 42, 48],
        cut: '5%',
        roi: '15 – 18%',
        allocation: [
            { label: 'Oven Industri', pct: 40, color: '#1E3A5F' },
            { label: 'Bahan Baku Mentah', pct: 30, color: '#00C853' },
            { label: 'Pemasaran Digital', pct: 20, color: '#FF9800' },
            { label: 'Operasional', pct: 10, color: '#6B7280' },
        ],
        roiRate: 0.17,
    }
];
